name: CI/CD for Portfolio Website

on:
  push:
    branches:
      - main
      - master
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - main
      - master
      - 'feature/*'
      - 'bugfix/*'

jobs:
  project-test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build project
        run: npm run build

  docker-build-and-push-image:
    needs: project-test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mazzlookman/books-management-api:latest